/*
 * To change this template, choose
            @Override
            public void setSelectedItem(Object anItem) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public Object getSelectedItem() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public int getSize() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public E getElementAt(int index) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void addListDataListener(ListDataListener l) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void removeListDataListener(ListDataListener l) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        }Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author aviad elitzur
 */
package myGUI;

import allcode.Post;
import connectionRMI.ConnectionInterface;
import myGUI.Registration;
//import rmi.RemoteImpl;
import connectionRMI.RMIclient;
import connectionRMI.RemoteInterface;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListModel;
import services.PostRMI;
import services.Response;
import services.report;

public class ForumGUI extends javax.swing.JFrame {

    public RemoteInterface _ci; 
    public int postIndex;
    public String[] forumsList= new String []{"food","ride", "sport", "computers", "life style"};
    /**
     * Creates new form NewJFrame
     */
    public ForumGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        titleField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        userName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        forumsComboBox = new javax.swing.JComboBox(forumsList);
        psotSubmit = new javax.swing.JButton();
        reports = new javax.swing.JLabel();
        enterSubForumButton = new javax.swing.JButton();
        write_post_title = new javax.swing.JLabel();
        choose_forum = new javax.swing.JLabel();
        choose_subforum = new javax.swing.JLabel();
        main_title = new javax.swing.JLabel();
        register_button = new javax.swing.JButton();
        adminButton = new javax.swing.JButton();
        connectButton = new javax.swing.JButton();
        enterPostButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        complainButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        subforumsList = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        postsTextArea = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        postNumberField = new javax.swing.JTextField();
        forgatPasswordLabel = new javax.swing.JLabel();
        questionLabel = new javax.swing.JLabel();
        answerTextField = new javax.swing.JTextField();
        questionButton = new javax.swing.JButton();
        moderatorButton = new javax.swing.JButton();
        editPostButton = new javax.swing.JButton();
        postInformationLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        login.setText("login");
        login.setEnabled(false);
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        logout.setText("logout");
        logout.setEnabled(false);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        titleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleFieldActionPerformed(evt);
            }
        });

        contentTextArea.setColumns(20);
        contentTextArea.setRows(5);
        jScrollPane1.setViewportView(contentTextArea);

        jLabel1.setText("title");

        jLabel2.setText("content");

        jLabel3.setText("name");

        jLabel4.setText("password");

        forumsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forumsComboBoxActionPerformed(evt);
            }
        });

        psotSubmit.setText("submit");
        psotSubmit.setEnabled(false);
        psotSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psotSubmitActionPerformed(evt);
            }
        });

        reports.setText("----reports----");

        enterSubForumButton.setText("enter sub forum");
        enterSubForumButton.setEnabled(false);
        enterSubForumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterSubForumButtonActionPerformed(evt);
            }
        });

        write_post_title.setText("write your post here:");

        choose_forum.setText("choose forum:");

        choose_subforum.setText("choose sub-forum in forum:");

        main_title.setBackground(new java.awt.Color(102, 102, 255));
        main_title.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        main_title.setText("welcome to forums site ");

        register_button.setText("register");
        register_button.setEnabled(false);
        register_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_buttonActionPerformed(evt);
            }
        });

        adminButton.setText("administrator functions");
        adminButton.setEnabled(false);
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        connectButton.setText("connect to server");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        enterPostButton.setText("enter post");
        enterPostButton.setEnabled(false);
        enterPostButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterPostButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("not registered yet?");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setText("login");

        complainButton.setText("complain on moderator");
        complainButton.setEnabled(false);
        complainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complainButtonActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(subforumsList);

        postsTextArea.setEditable(false);
        postsTextArea.setColumns(20);
        postsTextArea.setRows(5);
        jScrollPane4.setViewportView(postsTextArea);

        jLabel7.setText("choose number of post to see its responses:");

        forgatPasswordLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        forgatPasswordLabel.setText("forgat your password? press here");
        forgatPasswordLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgatPasswordLabelMouseClicked(evt);
            }
        });

        questionLabel.setText("--question--");

        answerTextField.setEnabled(false);

        questionButton.setText("check");
        questionButton.setEnabled(false);
        questionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionButtonActionPerformed(evt);
            }
        });

        moderatorButton.setText("moderator functions");
        moderatorButton.setEnabled(false);

        editPostButton.setText("edit post");
        editPostButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPostButtonActionPerformed(evt);
            }
        });

        postInformationLabel.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        postInformationLabel.setText("write post");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(reports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(257, 257, 257))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                            .addComponent(titleField))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(psotSubmit))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(write_post_title, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(choose_subforum)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(choose_forum)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(forumsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(enterSubForumButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(connectButton)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(postInformationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(postNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(editPostButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(enterPostButton, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(main_title, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(88, 88, 88)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(jLabel3)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(logout)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(login))
                                            .addComponent(userName)
                                            .addComponent(password)))
                                    .addComponent(forgatPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(register_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(complainButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adminButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(moderatorButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(questionButton)
                            .addComponent(answerTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(questionLabel)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(login)
                                    .addComponent(logout))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(forgatPasswordLabel)
                                .addGap(18, 18, 18)
                                .addComponent(questionLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(answerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(questionButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(main_title, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(choose_forum)
                                        .addComponent(forumsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(connectButton)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(choose_subforum)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(enterSubForumButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(postInformationLabel)
                                        .addGap(82, 82, 82))
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(359, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(write_post_title)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(psotSubmit)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(register_button)
                                .addGap(11, 11, 11)
                                .addComponent(moderatorButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adminButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(enterPostButton)
                                    .addComponent(postNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(complainButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(editPostButton)
                                .addGap(8, 8, 8)))
                        .addComponent(reports)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        report r;
        try {
            r = _ci.logout();
            reports.setText(r.toString());
        } catch (RemoteException ex) {
            Logger.getLogger(ForumGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
            
    }//GEN-LAST:event_loginActionPerformed

    private void psotSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psotSubmitActionPerformed
        try {
            if(titleField.getText().equals("") || contentTextArea.getText().equals("")){
                reports.setText("missing fields in title or content");
            }
            else{
                String state= postInformationLabel.getText();
                report r = report.FAIL;
                switch (state) {
                    case "write post":
                        r= _ci.writePost(titleField.getText(),contentTextArea.getText()).getReport();
                        break;
                    case "write response post":
                        r= _ci.writeResponsePost(titleField.getText(),contentTextArea.getText()).getReport();
                        break;
                    case "edit post":
                        r= _ci.postEdit(postIndex, titleField.getText(), contentTextArea.getText());
                        postInformationLabel.setText("write response post");
                        break;
                }
                titleField.setText("");
                contentTextArea.setText("");
                reports.setText(r.toString());
            }
        } catch (RemoteException ex) {
            Logger.getLogger(ForumGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_psotSubmitActionPerformed

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        String user,pass;
        user=userName.getText();
        pass=password.getText();
        if(user.equals("") || pass.equals(""))
            reports.setText("failed-empty user name or password");
        else{
            try {
                report r=_ci.login(user, pass);
                reports.setText(r.toString());
                if(r==report.OK){
                    userName.setText("");
                    password.setText("");
                }
            } catch (RemoteException ex) {
                Logger.getLogger(ForumGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_loginMouseClicked

    private void forumsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forumsComboBoxActionPerformed
        String forumName=(String) forumsComboBox.getSelectedItem();
        try {
            _ci.exitForum();
            Vector<String> subforums=_ci.getSubForums(forumName);
            subforumsList.setListData(subforums.toArray());
            report r=_ci.enterForum(forumName);
            reports.setText("enter forum " + forumName + ": " + r.toString());
            main_title.setText(forumName);
            postsTextArea.setText("");
            
        } catch (RemoteException ex) {
            Logger.getLogger(ForumGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_forumsComboBoxActionPerformed

    private void register_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_buttonActionPerformed
        Registration reg;
        try {
            reg = new Registration();
            reg.setVisible(true);
        } catch (RemoteException ex) {
            Logger.getLogger(ForumGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_register_buttonActionPerformed

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        _ci=RMIclient.getConnectionByFactory();
        if(_ci != null){
            Vector<String> forums;
            try {
                forums = _ci.getForums();
                forumsComboBox.setModel(new javax.swing.DefaultComboBoxModel<String>(forums));
                reports.setText("connetcion done");
                setButtensEnabled();
            } catch (RemoteException ex) {
                Logger.getLogger(ForumGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            reports.setText("connection failed");
        }
    }//GEN-LAST:event_connectButtonActionPerformed

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        try {
            AdminGUI admin=new AdminGUI();
            admin.setForum((String)forumsComboBox.getSelectedItem(), "", "");
            admin.setVisible(true);
        } catch (RemoteException ex) {
            Logger.getLogger(ForumGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
 
    }//GEN-LAST:event_adminButtonActionPerformed

    private void complainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complainButtonActionPerformed
               // TODO add your handling code here:
    }//GEN-LAST:event_complainButtonActionPerformed

    private void enterSubForumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterSubForumButtonActionPerformed
        try {
            _ci.exitSubforum();
            Response res=_ci.enterSubforum((String)subforumsList.getSelectedValue());
            main_title.setText((String)subforumsList.getSelectedValue());
            postInformationLabel.setText("write post");
            ArrayList <PostRMI> posts;
            if(res.getMe()!=null){
                postsTextArea.setText("");
                posts =(ArrayList<PostRMI>)res.getMe();
                for (Iterator<PostRMI> it = posts.iterator(); it.hasNext();) {
                    PostRMI p = it.next();
                    postsTextArea.setText(postsTextArea.getText()+ postFormat(p));
                }
            }
            //TODO
        } catch (RemoteException ex) {
            Logger.getLogger(ForumGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_enterSubForumButtonActionPerformed

    private void titleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleFieldActionPerformed

    private void forgatPasswordLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgatPasswordLabelMouseClicked
        answerTextField.setVisible(true);
        questionButton.setVisible(true);
        //answerTextField.setEditable(true);
        answerTextField.setEnabled(true);
        questionButton.setEnabled(true);
        try {
            questionLabel.setText(_ci.getMyQuestion(userName.getText()));
        } catch (RemoteException ex) {
            Logger.getLogger(ForumGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_forgatPasswordLabelMouseClicked

    private void questionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionButtonActionPerformed
        if(userName.getText().equals("") || answerTextField.getText().equals("")){
            reports.setText("missing field: please insert username and answer.");
        }
        else{
            try {
                report r=_ci.isValidAnswer(userName.getText(), answerTextField.getText());
                if(r==report.OK){
                    reports.setText("verification pass, you are logged now");
                    answerTextField.setVisible(false);
                    questionButton.setVisible(false);
                    questionLabel.setVisible(false);
                }
                else{
                    reports.setText(r.toString());
                }
                
                
            } catch (RemoteException ex) {
                Logger.getLogger(ForumGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            
        }
    }//GEN-LAST:event_questionButtonActionPerformed

    private void enterPostButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterPostButtonActionPerformed
        int index;
        String s=postNumberField.getText();
        postNumberField.setText("");
        if(!s.equals("")){
            try{
                 index=Integer.parseInt(s);
                 Response res= _ci.enterPost(index);
                 if(res.getReport() == report.OK){
                     ArrayList <PostRMI> posts;
                    postsTextArea.setText("");
                    posts =(ArrayList<PostRMI>)res.getMe();
                    if(!posts.isEmpty()){
                        for (Iterator<PostRMI> it = posts.iterator(); it.hasNext();) {
                            PostRMI p = it.next();
                            postsTextArea.setText(postsTextArea.getText()+ postFormat(p));
                        }
                    }//if
                    // labels change text
                     reports.setText("enter post " + index + " done");
                     main_title.setText("Post");
                     postInformationLabel.setText("write response post");
                    
                     //TODO: edit post
                 }
                 else{
                     reports.setText("enter post " + index + " failed");
                 }
            }catch(NumberFormatException | RemoteException e){
                reports.setText("please enter a number");
            }
        }else{
            reports.setText("enter post faild: enpty field");
        }
    }//GEN-LAST:event_enterPostButtonActionPerformed

    private void editPostButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPostButtonActionPerformed
        // get post from server by its index
        try{
            int index=Integer.parseInt(postNumberField.getText());
            PostRMI p = (PostRMI) _ci.getPostByIndex(index).getMe();
            if(p != null){
                titleField.setText(p.get_title());
                contentTextArea.setText(p.get_content());
                postIndex=index;
                postInformationLabel.setText("edit post");
            }
            else{
                reports.setText(_ci.getPostByIndex(index).getReport().toString());
            }
        }catch(Exception e){
            reports.setText("in valid post number");
        }
        //show it in post write option
        //set titles information
    }//GEN-LAST:event_editPostButtonActionPerformed

    public void setButtensEnabled(){
        enterPostButton.setEnabled(true);
        enterSubForumButton.setEnabled(true);
        psotSubmit.setEnabled(true);
        login.setEnabled(true);
        logout.setEnabled(true);
        register_button.setEnabled(true);
        
        //adminButton.setEnabled(true);
    }
    
    public String postFormat(PostRMI p){
        StringBuilder ans=new StringBuilder();
        ans.append("----------------\n");
        ans.append("post ").append(p.get_index());
        ans.append("> writen by: ").append(p.get_publisher()).append('\n');
        ans.append(p.get_title()).append('\n');
        ans.append(p.get_content()).append('\n');
        return ans.toString();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForumGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForumGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForumGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForumGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForumGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminButton;
    private javax.swing.JTextField answerTextField;
    private javax.swing.JLabel choose_forum;
    private javax.swing.JLabel choose_subforum;
    private javax.swing.JButton complainButton;
    private javax.swing.JButton connectButton;
    private javax.swing.JTextArea contentTextArea;
    private javax.swing.JButton editPostButton;
    private javax.swing.JButton enterPostButton;
    private javax.swing.JButton enterSubForumButton;
    private javax.swing.JLabel forgatPasswordLabel;
    private javax.swing.JComboBox forumsComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton login;
    private javax.swing.JButton logout;
    private javax.swing.JLabel main_title;
    private javax.swing.JButton moderatorButton;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel postInformationLabel;
    private javax.swing.JTextField postNumberField;
    private javax.swing.JTextArea postsTextArea;
    private javax.swing.JButton psotSubmit;
    private javax.swing.JButton questionButton;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JButton register_button;
    private javax.swing.JLabel reports;
    private javax.swing.JList subforumsList;
    private javax.swing.JTextField titleField;
    private javax.swing.JTextField userName;
    private javax.swing.JLabel write_post_title;
    // End of variables declaration//GEN-END:variables
}
